services:
  
  ingestion:
    networks:
      - elt_network
    build: ./ingestion
    volumes:
      - ./dbt/model_transformations/seeds:/app/model_transformations/seeds

  dbt:
    build: ./dbt
    networks:
      - elt_network
    volumes:
      - ./dbt/model_transformations:/usr/app/dbt
    depends_on:
      ingestion:
        condition: service_completed_successfully
    entrypoint: ["sh", "-c"]
    command: >
      "dbt deps --project-dir /usr/app/dbt --profiles-dir /usr/app/dbt &&
      dbt seed --project-dir /usr/app/dbt --profiles-dir /usr/app/dbt &&
      dbt run --project-dir /usr/app/dbt --profiles-dir /usr/app/dbt &&
      dbt test --project-dir /usr/app/dbt --profiles-dir /usr/app/dbt"

networks:
  elt_network:
    driver: bridge