version: 2

models:
  - name: staging_netflix_titles
    description: "The raw Netflix data has been transformed into cleaned and typed versions."
    columns:
      - name: show_id
        tests:
          - not_null
          - unique
      - name: type
        tests:
          - accepted_values:
              values: ["Movie", "Tv Show"]
      - name: title
      - name: director
      - name: actors
      - name: countries
      - name: date_added
      - name: release_year
      - name: rating
      - name: duration
      - name: duration_minutes
      - name: duration_seasons
      - name: genres_list
      - name: description
      - name: loaded_at
